#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:nil broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:nil tasks:t tex:t
#+OPTIONS: timestamp:nil title:t toc:nil todo:t |:t
#+TITLE: Intézeti értekezlet
#+DATE: <2023-10-03 k>
#+AUTHOR: Kalicz Péter
#+EMAIL: kaliczp@gmail.com
#+LANGUAGE: hu
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.9)


* Jelen
8.45 órától lenne, de kicsit késve kezdünk.
** Szobában
- KiGé
- HoTi
- KaPé
- BrGá
- PrPé
- CzKo 140 embernek előadást tart kicsit késik
- SzÁr
- BaTa

** Online
- HeAn
- ZKiKA
- KiBa

** Nincs


* Fehérvár stratégiai tárgyalás
Hirtelen jött. Hányan vannak Fehérváron?
Kornél később mondta: Zambó délig kéri az anyagot.

* Termek
Hétfőnként a 4-es teremben 5–7-ig Nagy Péter matek korrepetálást tart.
Kerüljön bele az órarendbe.

* Kutatók éjszakája
Köszöni mindent. Fotók kellenek. András vág ki.
Egyetemi szinten kellene szervezni.

Térképes segítség jó.

Tapasztalatnak jó volt.

Intézeti után a TV-t vissza kell vinni.

Híradóban is volt. Egyenesbe kerülnek a papírok.
Már a drónbiztosítás megvan.

* Petíció a fújó ellen
Hangos.

* BorderEye
Ma délután lesz megbeszélés.

Környezetértékelés is cikként bemegy.

* Összdolgozói
9:20–9:40-ig lesz.

5 dia külön szedve az oktatást, doktori tárgyak.

Inkább a kutatások megismerése a lényeg. Fel lehet sorolni,
három dia kutatásról.

Online részvételre lesz-e lehetőség?

Jó lenne, ha minél nagyobb létszámba részt vesz az Intézet.

* Lemorzsolódás, oktatás
Gábor meg fogja magyarázni.

Jánoska kérte online. Vadgazda.

* Szoftver beszerzés
Hirtelen jött levél az igényekről. Volt-e valami visszhang?

* Munkavédelmi bejárás
Október 16-án hétfőn. Tomi. Munkavédelmi összekötők. Segítsék a laborba bejutást.

* OEE Erdélyi helyi csoport
Október 19–21 erdészeti szakkonferencia.

Kommandó településen. Kézdivársárhely mellett. Régi sikló, kisvasút.

* Nemzeti Park
Meghívót küldöttek, tanulmányúttal egybekötött workshop 18–19 Sarród
kócsagvár és lászlómajor. Valami projekthez kapcsolódik.  Vizes
élőhelyes dolgok lennének. Efix szervezi.

* Kitüntetés
Bálint jelezte, hogy Kucsara Misit befogadták javaslatnak.

* Gy-M-S vármegyei Kereskedelmi és Ipari Kamara
Szakképzés kerekasztal. Jó gyakorlatok, képzési feladat.

* Gépjárműbeszerzés update
Kaptunk egy lekattintós árajánlatot. Excel táblában képletek
nem voltak lehúzva. Tímea javított 600 e Ft különbség.
Királynénál előterjesztésen. Nagyértékű beszerzés tervben nem volt.
Van raktáron. Szenátus, kuratórium.

6-án kuratórium, 5-én szenátus.

* Labor RRF
20-as gép sem jó.

Volt-e fejlemény. Pénteken lesz tájékoztató az RRF-ről a kari programban.

Labor ügyben tényleg lépni kellene. Vannak problémák egyetemi
szinten. Egyetemi fenntartású laborok legyenek rektor
szerint. Locsmándi Szabolcs: GT114 kész, levennék a kezüket.

Intézeti labor is jó lenne, és egyetemi szintű is.

Tanszéki kislabor is rossz állapotban. BorderEyeban lehet beszerezni.
Háttértárolót is terveztek. 2–3 desktob gép és tárolók 6-15 tera.

Primusz P-ék lekkattintahtós gépet vettek 2 milliós 2 gép nem olyan jó.
Sokkal jobb videókártyát lehetett volna venni.

GINOP speciális négy év alatt nem ment. Windows 10-et is itt tették rá.

* Beszerzés
Fluente még nem indult a TKP-ben, de lesz mérleg. 
Gyártótól tud beszerezni.

Stipendiumos keret 400 eFt költhető keret van az intézetnek.
Abdulrahmannak is kell. Konferencia, publikáció, ami elősegíti
a külföldi hallgatók továbbtanulását. Lakatos Barbara ismeri a
működését. Két részre kötődik. Ha nem használjuk az Egyetem
benyeli.

* Jogosultság
Szeptember 29-én ment fel a levél a kar részéről.

* Projekthét
Péterék is indítottak egyet 15 fővel. Összejött a 48 plusz fő.

Csak egy legyen tanévenként.

Most Veronika a Kari összekötő.

* Levelező földmérő
Sokszor előkerült.
Kredit ráképzés öngól. Mindenki munka mellett akarja csinálni.

Fehérváron ott a honlap.

* Botond
9-től van.

* Szonda tönkrement
Farkasárokban bedöglött az egyik szonda.

Stick leesett. Tomi visszarakja.

* Szakérnöki meghírdetés
Jövő szeptemberre van előirányozva. Erdész kreditgyűjtő.
Kezdik elfogadni. Tudunk ez ellen tiltakozni.
