#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:nil broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:nil tasks:t tex:t
#+OPTIONS: timestamp:nil title:t toc:nil todo:t |:t
#+TITLE: Intézeti értekezlet
#+DATE: <2023-10-03 k>
#+AUTHOR: Kalicz Péter
#+EMAIL: kaliczp@gmail.com
#+LANGUAGE: hu
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.9)


* Jelen
8.45 órától lenne, de kicsit késve kezdünk.
** Szobában
- KiGé
- HoTi
- KaPé
- BrGá
- PrPé
- CzKo 140 embernek előadást tart kicsit késik
- SzÁr
- BaTa

** Online
- HeAn
- ZKiKA
- KiBa

** Nincs


* Fehérvár stratégiai tárgyalás
Hirtelen jött. Hányan vannak Fehérváron?

* Termek
Hétfőnként a 4-es teremben 5–7-ig Nagy Péter matek korrepetálást tart.
Kerüljön bele az órarendbe.

* Kutatók éjszakája
Köszöni mindent. Fotók kellenek. András vág ki.
Egyetemi szinten kellene szervezni.

Térképes segítség jó.

Tapasztalatnak jó volt.

Intézeti után a TV-t vissza kell vinni.

Híradóban is volt. Egyenesbe kerülnek a papírok.
Már a drónbiztosítás megvan.

* Petíció a fújó ellen
Hangos.

* BorderEye
Ma délután lesz megbeszélés.

Környezetértékelés is cikként bemegy.

* Összdolgozói
9:20–9:40-ig lesz.

5 dia külön szedve az oktatást, doktori tárgyak.

Inkább a kutatások megismerése a lényeg. Fel lehet sorolni,
három dia kutatásról.

Online részvételre lesz-e lehetőség?

Jó lenne, ha minél nagyobb létszámba részt vesz az Intézet.

* Lemorzsolódás, oktatás
Gábor meg fogja magyarázni.

Jánoska kérte online. Vadgazda.

* Szoftver beszerzés
Hirtelen jött levél az igényekről. Volt-e valami visszhang?

* Munkavédelmi bejárás
Október 16-án hétfőn. Tomi. Munkavédelmi összekötők. Segítsék a laborba bejutást.

* OEE Erdélyi helyi csoport
Október 19–21 erdészeti szakkonferencia.

Kommandó településen. Kézdivársárhely mellett. Régi sikló, kisvasút.

* Nemzeti Park
Meghívót küldöttek, tanulmányúttal egybekötött workshop 18–19 Sarród
kócsagvár és lászlómajor. Valami projekthez kapcsolódik.  Vizes
élőhelyes dolgok lennének. Efix szervezi.

* Kitüntetés
Bálint jelezte, hogy Kucsara Misit befogadták javaslatnak.

* Gy-M-S vármegyei Kereskedelmi és Ipari Kamara
Szakképzés kerekasztal. Jó gyakorlatok, képzési feladat.

