
* <2023-10-06 p>

** fELVEZETŐ
Dékáni öröm. Bemutatkozás. Infomáció adás. Összetartás intézetek között is.

** ETEGI
Lakatos Feri

REngeteg vendégelőadó.
WoS/Scopus 54 amiből sok D1–Q2

** GKI
Kornél

Geobioinformatikát már futóként mutatta.

** KTI
Rétfalvi Tamás

Hogyan lehet 7-9 fő hallgató / tárgy.

ESG Materialitási Kutatócsoport – széles spektrumú kollégákat keresnek.

REFOREST bajti döntéstámogató modellhez hozam és biodiveriztás vizsgálatok

Volt egy másik is.

Adri VEAB Élettudomány kategóriában.

** Vadgáz
Jánoska Feri

Danás Máté intézeti mérnök

** Szünet
40-ig.

** HÖK
- Kele Zsombor
- Csorba Mátyás
- Fekete Gellért

Kommunikáció, oktató értékelés.
Mentor program.

Újra dolgozva.

** Szakkoli

** Ökoklub

** Dékáni összegzés
Demonstrátori rendszer. Oktató-hallgató párbeszéd.

** Digitális transzformáció 2022–26
RRF-2.1.2-21-2022-00011
Tímár Andi

Uniós forrás. Újraindítási alapból.

2 md Ft forrás

11 tevékenység. 3 munkacsoportba:
- Oktatási
- Informatikai
- Nemzetközi

*** Informatikai és nemzetközi
Indikátorok digitlis eszközök, készségfejlesztés, intelligens szakosodás vagy képzés.

WiFi fejlesztés 2022 nyarán. 

Projekt informatikai fejlesztési terve 24 VI. 30. be kell szerezni. Október informatikai
közbeszerzés.

Blended Learning menedzsment rendsezr.

Hibrid oktatás oktató és hallgató hangjának rögzítése!

Laborok. Lewinszky gyerekmegfigyelő, EMK geobioinformatikai és terepdiagnosztikai.

könyvtári szolgáltatás. Online tananyagok 6 db kurzus

Fenntarthatóság a nemzetközi rangsorokhoz:
Kerékpáros barát is!

Publikációs pályázati felhívások.

*** Oktatási
Pár Dávid örül, hogy szélesebb körben lehet beszélni.

EMK digitális oktatási stratégiája. 

**** Digitális Oktatásmódszertani Központ
Projektben és azon túl támogatás

Jó gyakorlatok és módszertani ajánlások. Digitális szakértő, e-learning szakértő,

Most nincs digitális portfóli Pécsi, Károli, Egri, Pannon.

IKT pedagógia, ottani szakértők. Workshopok és kurzusok elarning, jelenlét, blended learning.
Kurzus minták. A jövőben saját tananyagokat átültetni.

**** Digitális tananyagok fejlesztése Moodle környezetben
Nem a legfrisebb. Frissíteni fogják a DE vezetésével!
Teams és neptun integrációval. Átlátszóbb formájú integráció lesz.
Távoktatási vagy blended learning fejlesztés! Minden kar bevonásra kerül.

Elvárások megfogalmazásra kerültek. Nem lehet uniform fejlesztés. Team munka
szereplője oktató. Pedagógiai és elearning...

Megvan, hogy kivel kapcsolódhatnak.

**** Molekuláris oktatás digitális tananyagainak fejlesztése (Course Garden)
Szűkebb anyag. Horváth Adrienn tapasztalt felhasználó.
Fenntarthatóság és innováció, valamint geobioinformatika.

Elméleti tananyag fejlesztés és projekt.

**** Tantervmodernizálás
Nem digitális tananyag fejlesztés. Második tanterv. Polgár András és Balázs Pál.

Külső tanácsadó cég (PVC?). EU-s tanácsadó cég, milyen munkakörökbe mennek a hallgatók, piac
milyen elvárásokat nyújt? A cég átadja a szaktudást.

**** Intelligens szakosodás
Ezt adta a Kormány.

digitális képzés, kommunikáció, kutatásmenedzsment.

Szabad a pálya. Volt igényfelmérés. Több igényfelmérés. Szélesebb körben kiterjesztés.

Kurzus részvétel nem csak oktatóknak. Hallgatóknak plusz a tananyagon
felül. Belsős kollégák kínálják fel.

Lehet kurzusfejlesztési ötlettel jelentkezni. Minél többen
elvégezzék. Komoly indikátor számok. Nem ingyen!

Dékán: egyre több kollégát szólítanak meg. Egyéni felelősségvállalás.

** Dékán
Munkánk eredménye.

*** Oktatás
Fontos értékmérője mennyire választanak? Felvételi.

Jelentkezők száma KEKVA szerződés. Környész bizonyított. Angol MSc
Levelező MSc ezért indult magyarul.

Komoly plusz létszám. Felvételei átalakulása. Bízik a stabil létszámban.
Várható szakközépben nő egy évvel a technikus. 50% szakközép, erdőmérnök 2/3!
Remélhetőleg nem rontja a finanszírozást.

Stratégiai döntés minimum pontszám megszabva.

Külföldi SH ösztöndíj rendszer. 5 fő iratkozott be.

PhD nagyobb súly. Ált: 12% külfödi, PhD 2x%

Saját példája németroszági.

*** Gazdasági
Június végi állás. Korábban befizetni. Most könnyebb dolog. Finanszírozás bérekre kiterjedt.
Stabilan jönnek. Fenntartás is központi ktgvetésből. Sikerült új kollégákat felvenni.
30 év alatt hiányosság. Figyelni! Mennyi hallgató a PhDból marad itt?

Sokszor csak mérnöki szintű munkára kérnek árajánlatot.

Speciális támogatások 40 mio-s növekedés. Saját erős fejlesztések.

Energia válság, de most 2.3 md beruházás. Megújuló energiás beruházás.

TAEGnek is előnyt hozott az új rendszer.

Augusztus plusz vizsgák kiírása. Elmaradás volt. Kreditek ne kerültek beírásra,
ennek eredménye, hogy megfelelő kredit lett +300 mio.

Kari összesítés publikáció VIII. 31. 

GKI 22516 MTID

45 cikkes kari konferencia. Jövő februárban újra erdészettudományi konferencia.
Saját egyéni felelősség!

*** További teendők
CV-s vizsgák indulnak. Lemorzsolódás megszüntetése fontos.

100-ból 35 nem végez országos szinten!

Nagy problémákkal küzdünk. Komoly problémák, elakadások. Több oktató
is vizsgáztasson egy tárgyból. Bevonni a kollégákat! Objektív minőségbiztosítás.

Támogassuk az oktatói munkát. Demonstrátori munka. Nem kutatási projekt kisegítő,
oktatási céllal! Azonnal érvényesül az oktatásban. Fontos.

Ha működik, akkor nagyobb forrás lesz!

Projekthét az EMK vezetésével. Négy dékán kéri, hogy évente egyszer. Kitöltve a bevonható létszám.

*** Kutatás
QS rangsor. Világranglistán 1000 publikáció. Mo.-i rangsroban 12-ek vagyunk.

Finanszírozási többlet.

RRF, Neumann J. program.

Náhlik Sepsiszentgyörgyi magyar erdész. Erasmus+ keretek! Oktatási feladatok.

NFK-s képzések erdészeti vonalon. Ágazati tudásközponttal. EMK szolgáltatni fog.
Érdemi finanszírozás 10e Ft/óra.

Erfurti akkreditált képzés.

Portfólió. Bemutatkozás. Nemzetközi Együttűködés.

*** FMK átalakulás
Nem volt nyugis ott az átalakulás. FMK alapvetően szolgáltatás centrikusan alakult át.
Dékán az oktatás-kutatás centrikusságot hangsúlyozza. Nem tartja kívánatosnak a változtatást.

Azért lehet szervezeti fejlesztés. Polgár András, Sipos Gyuri.

Stabilnak tűnő gazdálkodás.

Járművek beszerzése. KTI terepjáró indulhat, földmunkagép elindul.
Kari kisbusz 9 fős a karon. Kari kulcsos autó!!! GKI felmerült Suzuki jövő év elejére.
Vagyongazdálkodási tervben rábólintanak, akkor. Szigorú gazdasági működés.

*** Honlap
megújult. Nézzük át a honlap tartalmait. Nincs kommunikációs munkatárs.
Tartalmakat átnézni. Dékáni hivatalon keresztül. Naprakésznek lenni!

*** Honoris causa
Karok adományozható. Elsősorban a nemzetközi kapcsolatépítés. Nem terjesztették
elő. FMK japán professzor. Gondoljuk át a kapcsolatok alapján. Jövőben, érdemben segít.
Nagyon híres személyt.

*** Hallgató toborzás
Tavalyi toborzó kampány hol hozott eredményt. Novembertől nyílt napok. Cél a minőségi
fejlesztés! Sajnos sok szakközepes, gyenge alappal. Fontos lenne jó gimikből! Diákok
nem tudják, hogy mit kezdjenek magukkal. Kiadványok ehhez! Prospektus szerkesztés.
Kari szintű kiadványok az egyetemi mellett. László Richárd Facebook kampány. Ma már
más fórum.

EUs konferencia. Nemzetközi kapcsolatépítés.

** Kérdések

Zsákai Balázs a honlap felelős.

Intézeti gazdálkodás? Saját munka gyümölcse visszacsapódik.
Be fog következni.

** Felvi
Új alapokon. Csomó dolog átkerül az egyetemre. Mi van a honlapon a szakról?
Izgalmas tartalom.
